// scripts/GenStyledCva.res - Native ReScript Codegen Script for @styled-cva/react

module Fs = {
  @module("node:fs") external writeFileSync: (string, string, string) => unit = "writeFileSync"
}

module Path = {
  @module("node:path") external join: (string, string, string) => string = "join"
}

module Process = {
  @val external cwd: unit => string = "process.cwd"
}

let elements = [
  "a",
  "abbr",
  "address",
  "article",
  "aside",
  "audio",
  "b",
  "blockquote",
  "button",
  "canvas",
  "caption",
  "cite",
  "code",
  "dd",
  "del",
  "details",
  "dfn",
  "dialog",
  "div",
  "dl",
  "dt",
  "em",
  "fieldset",
  "figcaption",
  "figure",
  "footer",
  "form",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "header",
  "hgroup",
  "hr",
  "i",
  "img",
  "input",
  "ins",
  "kbd",
  "label",
  "legend",
  "li",
  "main",
  "mark",
  "nav",
  "ol",
  "p",
  "picture",
  "pre",
  "progress",
  "q",
  "section",
  "select",
  "small",
  "span",
  "strong",
  "sub",
  "summary",
  "sup",
  "table",
  "tbody",
  "td",
  "textarea",
  "tfoot",
  "th",
  "thead",
  "time",
  "tr",
  "ul",
  "video",
]

let escapeName = (name: string): string => {
  switch name {
  | "open" | "type" | "rec" | "mod" | "let" | "in" | "for" | "while" => "_" ++ name
  | _ => name
  }
}

let generateBindings = (): string => {
  let bindings =
    elements
    ->Array.map(el => {
      "  @module(\"@styled-cva/react\") @scope(\"default\")\n  external " ++
      escapeName(el) ++
      ": (string, 'config) => React.component<'props> = \"" ++
      el ++ "\""
    })
    ->Array.join("\n\n")

  "// StyledCva.res - Codegenerated ReScript v12 Bindings for @styled-cva/react\n" ++
  "// Auto-generated by scripts/GenStyledCva.res. DO NOT EDIT DIRECTLY.\n\n" ++
  "@module(\"@styled-cva/react\") @variadic\n" ++
  "external cn: array<string> => string = \"cn\"\n\n" ++
  "@module(\"@styled-cva/react\")\n" ++
  "external cva: (string, 'config) => ('props => string) = \"cva\"\n\n" ++
  "module Tw = {\n" ++
  bindings ++
  "\n\n" ++
  "  @module(\"@styled-cva/react\")\n" ++
  "  external custom: (React.component<'props>, string, 'config) => React.component<'props> = \"default\"\n" ++ "}\n"
}

let main = () => {
  let outputPath = Path.join(Process.cwd(), "src", "StyledCva.res")
  let content = generateBindings()
  Fs.writeFileSync(outputPath, content, "utf8")
  Console.log(
    "✅ Generated " ++
    Int.toString(elements->Array.length) ++
    " HTML element bindings in " ++
    outputPath,
  )
}

main()
