// StyledCva.res - Codegenerated ReScript v12 Bindings for @styled-cva/react
// Auto-generated by scripts/GenStyledCva.res. DO NOT EDIT DIRECTLY.

type styledProps = {
  className?: string,
  children?: React.element,
  onClick?: JsxEvent.Mouse.t => unit,
  href?: string,
  target?: string,
  rel?: string,
}

@module("@styled-cva/react") @variadic
external cn: array<string> => string = "cn"

@module("@styled-cva/react")
external cva: (string, 'config) => 'props => string = "cva"

module Tw = {
  @module("@styled-cva/react") @scope("default")
  external a: string => React.component<styledProps> = "a"

  @module("@styled-cva/react") @scope("default")
  external aWithConfig: (string, 'config) => React.component<styledProps> = "a"

  @module("@styled-cva/react") @scope("default")
  external abbr: string => React.component<styledProps> = "abbr"

  @module("@styled-cva/react") @scope("default")
  external abbrWithConfig: (string, 'config) => React.component<styledProps> = "abbr"

  @module("@styled-cva/react") @scope("default")
  external address: string => React.component<styledProps> = "address"

  @module("@styled-cva/react") @scope("default")
  external addressWithConfig: (string, 'config) => React.component<styledProps> = "address"

  @module("@styled-cva/react") @scope("default")
  external article: string => React.component<styledProps> = "article"

  @module("@styled-cva/react") @scope("default")
  external articleWithConfig: (string, 'config) => React.component<styledProps> = "article"

  @module("@styled-cva/react") @scope("default")
  external aside: string => React.component<styledProps> = "aside"

  @module("@styled-cva/react") @scope("default")
  external asideWithConfig: (string, 'config) => React.component<styledProps> = "aside"

  @module("@styled-cva/react") @scope("default")
  external audio: string => React.component<styledProps> = "audio"

  @module("@styled-cva/react") @scope("default")
  external audioWithConfig: (string, 'config) => React.component<styledProps> = "audio"

  @module("@styled-cva/react") @scope("default")
  external b: string => React.component<styledProps> = "b"

  @module("@styled-cva/react") @scope("default")
  external bWithConfig: (string, 'config) => React.component<styledProps> = "b"

  @module("@styled-cva/react") @scope("default")
  external blockquote: string => React.component<styledProps> = "blockquote"

  @module("@styled-cva/react") @scope("default")
  external blockquoteWithConfig: (string, 'config) => React.component<styledProps> = "blockquote"

  @module("@styled-cva/react") @scope("default")
  external button: string => React.component<styledProps> = "button"

  @module("@styled-cva/react") @scope("default")
  external buttonWithConfig: (string, 'config) => React.component<styledProps> = "button"

  @module("@styled-cva/react") @scope("default")
  external canvas: string => React.component<styledProps> = "canvas"

  @module("@styled-cva/react") @scope("default")
  external canvasWithConfig: (string, 'config) => React.component<styledProps> = "canvas"

  @module("@styled-cva/react") @scope("default")
  external caption: string => React.component<styledProps> = "caption"

  @module("@styled-cva/react") @scope("default")
  external captionWithConfig: (string, 'config) => React.component<styledProps> = "caption"

  @module("@styled-cva/react") @scope("default")
  external cite: string => React.component<styledProps> = "cite"

  @module("@styled-cva/react") @scope("default")
  external citeWithConfig: (string, 'config) => React.component<styledProps> = "cite"

  @module("@styled-cva/react") @scope("default")
  external code: string => React.component<styledProps> = "code"

  @module("@styled-cva/react") @scope("default")
  external codeWithConfig: (string, 'config) => React.component<styledProps> = "code"

  @module("@styled-cva/react") @scope("default")
  external dd: string => React.component<styledProps> = "dd"

  @module("@styled-cva/react") @scope("default")
  external ddWithConfig: (string, 'config) => React.component<styledProps> = "dd"

  @module("@styled-cva/react") @scope("default")
  external del: string => React.component<styledProps> = "del"

  @module("@styled-cva/react") @scope("default")
  external delWithConfig: (string, 'config) => React.component<styledProps> = "del"

  @module("@styled-cva/react") @scope("default")
  external details: string => React.component<styledProps> = "details"

  @module("@styled-cva/react") @scope("default")
  external detailsWithConfig: (string, 'config) => React.component<styledProps> = "details"

  @module("@styled-cva/react") @scope("default")
  external dfn: string => React.component<styledProps> = "dfn"

  @module("@styled-cva/react") @scope("default")
  external dfnWithConfig: (string, 'config) => React.component<styledProps> = "dfn"

  @module("@styled-cva/react") @scope("default")
  external dialog: string => React.component<styledProps> = "dialog"

  @module("@styled-cva/react") @scope("default")
  external dialogWithConfig: (string, 'config) => React.component<styledProps> = "dialog"

  @module("@styled-cva/react") @scope("default")
  external div: string => React.component<styledProps> = "div"

  @module("@styled-cva/react") @scope("default")
  external divWithConfig: (string, 'config) => React.component<styledProps> = "div"

  @module("@styled-cva/react") @scope("default")
  external dl: string => React.component<styledProps> = "dl"

  @module("@styled-cva/react") @scope("default")
  external dlWithConfig: (string, 'config) => React.component<styledProps> = "dl"

  @module("@styled-cva/react") @scope("default")
  external dt: string => React.component<styledProps> = "dt"

  @module("@styled-cva/react") @scope("default")
  external dtWithConfig: (string, 'config) => React.component<styledProps> = "dt"

  @module("@styled-cva/react") @scope("default")
  external em: string => React.component<styledProps> = "em"

  @module("@styled-cva/react") @scope("default")
  external emWithConfig: (string, 'config) => React.component<styledProps> = "em"

  @module("@styled-cva/react") @scope("default")
  external fieldset: string => React.component<styledProps> = "fieldset"

  @module("@styled-cva/react") @scope("default")
  external fieldsetWithConfig: (string, 'config) => React.component<styledProps> = "fieldset"

  @module("@styled-cva/react") @scope("default")
  external figcaption: string => React.component<styledProps> = "figcaption"

  @module("@styled-cva/react") @scope("default")
  external figcaptionWithConfig: (string, 'config) => React.component<styledProps> = "figcaption"

  @module("@styled-cva/react") @scope("default")
  external figure: string => React.component<styledProps> = "figure"

  @module("@styled-cva/react") @scope("default")
  external figureWithConfig: (string, 'config) => React.component<styledProps> = "figure"

  @module("@styled-cva/react") @scope("default")
  external footer: string => React.component<styledProps> = "footer"

  @module("@styled-cva/react") @scope("default")
  external footerWithConfig: (string, 'config) => React.component<styledProps> = "footer"

  @module("@styled-cva/react") @scope("default")
  external form: string => React.component<styledProps> = "form"

  @module("@styled-cva/react") @scope("default")
  external formWithConfig: (string, 'config) => React.component<styledProps> = "form"

  @module("@styled-cva/react") @scope("default")
  external h1: string => React.component<styledProps> = "h1"

  @module("@styled-cva/react") @scope("default")
  external h1WithConfig: (string, 'config) => React.component<styledProps> = "h1"

  @module("@styled-cva/react") @scope("default")
  external h2: string => React.component<styledProps> = "h2"

  @module("@styled-cva/react") @scope("default")
  external h2WithConfig: (string, 'config) => React.component<styledProps> = "h2"

  @module("@styled-cva/react") @scope("default")
  external h3: string => React.component<styledProps> = "h3"

  @module("@styled-cva/react") @scope("default")
  external h3WithConfig: (string, 'config) => React.component<styledProps> = "h3"

  @module("@styled-cva/react") @scope("default")
  external h4: string => React.component<styledProps> = "h4"

  @module("@styled-cva/react") @scope("default")
  external h4WithConfig: (string, 'config) => React.component<styledProps> = "h4"

  @module("@styled-cva/react") @scope("default")
  external h5: string => React.component<styledProps> = "h5"

  @module("@styled-cva/react") @scope("default")
  external h5WithConfig: (string, 'config) => React.component<styledProps> = "h5"

  @module("@styled-cva/react") @scope("default")
  external h6: string => React.component<styledProps> = "h6"

  @module("@styled-cva/react") @scope("default")
  external h6WithConfig: (string, 'config) => React.component<styledProps> = "h6"

  @module("@styled-cva/react") @scope("default")
  external header: string => React.component<styledProps> = "header"

  @module("@styled-cva/react") @scope("default")
  external headerWithConfig: (string, 'config) => React.component<styledProps> = "header"

  @module("@styled-cva/react") @scope("default")
  external hgroup: string => React.component<styledProps> = "hgroup"

  @module("@styled-cva/react") @scope("default")
  external hgroupWithConfig: (string, 'config) => React.component<styledProps> = "hgroup"

  @module("@styled-cva/react") @scope("default")
  external hr: string => React.component<styledProps> = "hr"

  @module("@styled-cva/react") @scope("default")
  external hrWithConfig: (string, 'config) => React.component<styledProps> = "hr"

  @module("@styled-cva/react") @scope("default")
  external i: string => React.component<styledProps> = "i"

  @module("@styled-cva/react") @scope("default")
  external iWithConfig: (string, 'config) => React.component<styledProps> = "i"

  @module("@styled-cva/react") @scope("default")
  external img: string => React.component<styledProps> = "img"

  @module("@styled-cva/react") @scope("default")
  external imgWithConfig: (string, 'config) => React.component<styledProps> = "img"

  @module("@styled-cva/react") @scope("default")
  external input: string => React.component<styledProps> = "input"

  @module("@styled-cva/react") @scope("default")
  external inputWithConfig: (string, 'config) => React.component<styledProps> = "input"

  @module("@styled-cva/react") @scope("default")
  external ins: string => React.component<styledProps> = "ins"

  @module("@styled-cva/react") @scope("default")
  external insWithConfig: (string, 'config) => React.component<styledProps> = "ins"

  @module("@styled-cva/react") @scope("default")
  external kbd: string => React.component<styledProps> = "kbd"

  @module("@styled-cva/react") @scope("default")
  external kbdWithConfig: (string, 'config) => React.component<styledProps> = "kbd"

  @module("@styled-cva/react") @scope("default")
  external label: string => React.component<styledProps> = "label"

  @module("@styled-cva/react") @scope("default")
  external labelWithConfig: (string, 'config) => React.component<styledProps> = "label"

  @module("@styled-cva/react") @scope("default")
  external legend: string => React.component<styledProps> = "legend"

  @module("@styled-cva/react") @scope("default")
  external legendWithConfig: (string, 'config) => React.component<styledProps> = "legend"

  @module("@styled-cva/react") @scope("default")
  external li: string => React.component<styledProps> = "li"

  @module("@styled-cva/react") @scope("default")
  external liWithConfig: (string, 'config) => React.component<styledProps> = "li"

  @module("@styled-cva/react") @scope("default")
  external main: string => React.component<styledProps> = "main"

  @module("@styled-cva/react") @scope("default")
  external mainWithConfig: (string, 'config) => React.component<styledProps> = "main"

  @module("@styled-cva/react") @scope("default")
  external mark: string => React.component<styledProps> = "mark"

  @module("@styled-cva/react") @scope("default")
  external markWithConfig: (string, 'config) => React.component<styledProps> = "mark"

  @module("@styled-cva/react") @scope("default")
  external nav: string => React.component<styledProps> = "nav"

  @module("@styled-cva/react") @scope("default")
  external navWithConfig: (string, 'config) => React.component<styledProps> = "nav"

  @module("@styled-cva/react") @scope("default")
  external ol: string => React.component<styledProps> = "ol"

  @module("@styled-cva/react") @scope("default")
  external olWithConfig: (string, 'config) => React.component<styledProps> = "ol"

  @module("@styled-cva/react") @scope("default")
  external p: string => React.component<styledProps> = "p"

  @module("@styled-cva/react") @scope("default")
  external pWithConfig: (string, 'config) => React.component<styledProps> = "p"

  @module("@styled-cva/react") @scope("default")
  external picture: string => React.component<styledProps> = "picture"

  @module("@styled-cva/react") @scope("default")
  external pictureWithConfig: (string, 'config) => React.component<styledProps> = "picture"

  @module("@styled-cva/react") @scope("default")
  external pre: string => React.component<styledProps> = "pre"

  @module("@styled-cva/react") @scope("default")
  external preWithConfig: (string, 'config) => React.component<styledProps> = "pre"

  @module("@styled-cva/react") @scope("default")
  external progress: string => React.component<styledProps> = "progress"

  @module("@styled-cva/react") @scope("default")
  external progressWithConfig: (string, 'config) => React.component<styledProps> = "progress"

  @module("@styled-cva/react") @scope("default")
  external q: string => React.component<styledProps> = "q"

  @module("@styled-cva/react") @scope("default")
  external qWithConfig: (string, 'config) => React.component<styledProps> = "q"

  @module("@styled-cva/react") @scope("default")
  external section: string => React.component<styledProps> = "section"

  @module("@styled-cva/react") @scope("default")
  external sectionWithConfig: (string, 'config) => React.component<styledProps> = "section"

  @module("@styled-cva/react") @scope("default")
  external select: string => React.component<styledProps> = "select"

  @module("@styled-cva/react") @scope("default")
  external selectWithConfig: (string, 'config) => React.component<styledProps> = "select"

  @module("@styled-cva/react") @scope("default")
  external small: string => React.component<styledProps> = "small"

  @module("@styled-cva/react") @scope("default")
  external smallWithConfig: (string, 'config) => React.component<styledProps> = "small"

  @module("@styled-cva/react") @scope("default")
  external span: string => React.component<styledProps> = "span"

  @module("@styled-cva/react") @scope("default")
  external spanWithConfig: (string, 'config) => React.component<styledProps> = "span"

  @module("@styled-cva/react") @scope("default")
  external strong: string => React.component<styledProps> = "strong"

  @module("@styled-cva/react") @scope("default")
  external strongWithConfig: (string, 'config) => React.component<styledProps> = "strong"

  @module("@styled-cva/react") @scope("default")
  external sub: string => React.component<styledProps> = "sub"

  @module("@styled-cva/react") @scope("default")
  external subWithConfig: (string, 'config) => React.component<styledProps> = "sub"

  @module("@styled-cva/react") @scope("default")
  external summary: string => React.component<styledProps> = "summary"

  @module("@styled-cva/react") @scope("default")
  external summaryWithConfig: (string, 'config) => React.component<styledProps> = "summary"

  @module("@styled-cva/react") @scope("default")
  external sup: string => React.component<styledProps> = "sup"

  @module("@styled-cva/react") @scope("default")
  external supWithConfig: (string, 'config) => React.component<styledProps> = "sup"

  @module("@styled-cva/react") @scope("default")
  external table: string => React.component<styledProps> = "table"

  @module("@styled-cva/react") @scope("default")
  external tableWithConfig: (string, 'config) => React.component<styledProps> = "table"

  @module("@styled-cva/react") @scope("default")
  external tbody: string => React.component<styledProps> = "tbody"

  @module("@styled-cva/react") @scope("default")
  external tbodyWithConfig: (string, 'config) => React.component<styledProps> = "tbody"

  @module("@styled-cva/react") @scope("default")
  external td: string => React.component<styledProps> = "td"

  @module("@styled-cva/react") @scope("default")
  external tdWithConfig: (string, 'config) => React.component<styledProps> = "td"

  @module("@styled-cva/react") @scope("default")
  external textarea: string => React.component<styledProps> = "textarea"

  @module("@styled-cva/react") @scope("default")
  external textareaWithConfig: (string, 'config) => React.component<styledProps> = "textarea"

  @module("@styled-cva/react") @scope("default")
  external tfoot: string => React.component<styledProps> = "tfoot"

  @module("@styled-cva/react") @scope("default")
  external tfootWithConfig: (string, 'config) => React.component<styledProps> = "tfoot"

  @module("@styled-cva/react") @scope("default")
  external th: string => React.component<styledProps> = "th"

  @module("@styled-cva/react") @scope("default")
  external thWithConfig: (string, 'config) => React.component<styledProps> = "th"

  @module("@styled-cva/react") @scope("default")
  external thead: string => React.component<styledProps> = "thead"

  @module("@styled-cva/react") @scope("default")
  external theadWithConfig: (string, 'config) => React.component<styledProps> = "thead"

  @module("@styled-cva/react") @scope("default")
  external time: string => React.component<styledProps> = "time"

  @module("@styled-cva/react") @scope("default")
  external timeWithConfig: (string, 'config) => React.component<styledProps> = "time"

  @module("@styled-cva/react") @scope("default")
  external tr: string => React.component<styledProps> = "tr"

  @module("@styled-cva/react") @scope("default")
  external trWithConfig: (string, 'config) => React.component<styledProps> = "tr"

  @module("@styled-cva/react") @scope("default")
  external ul: string => React.component<styledProps> = "ul"

  @module("@styled-cva/react") @scope("default")
  external ulWithConfig: (string, 'config) => React.component<styledProps> = "ul"

  @module("@styled-cva/react") @scope("default")
  external video: string => React.component<styledProps> = "video"

  @module("@styled-cva/react") @scope("default")
  external videoWithConfig: (string, 'config) => React.component<styledProps> = "video"

  @module("@styled-cva/react")
  external custom: (React.component<'props>, string) => React.component<styledProps> = "default"

  @module("@styled-cva/react")
  external customWithConfig: (
    React.component<'props>,
    string,
    'config,
  ) => React.component<styledProps> = "default"
}
