// StyledCva.res - Codegenerated ReScript v12 Bindings for @styled-cva/react
// Auto-generated by scripts/generate-styled-cva.js. DO NOT EDIT DIRECTLY.

@module("@styled-cva/react") @variadic
external cn: array<string> => string = "cn"

@module("@styled-cva/react")
external cva: (string, 'config) => 'props => string = "cva"

module Tw = {
  @module("@styled-cva/react") @scope("default")
  external a: (string, 'config) => React.component<'props> = "a"

  @module("@styled-cva/react") @scope("default")
  external abbr: (string, 'config) => React.component<'props> = "abbr"

  @module("@styled-cva/react") @scope("default")
  external address: (string, 'config) => React.component<'props> = "address"

  @module("@styled-cva/react") @scope("default")
  external article: (string, 'config) => React.component<'props> = "article"

  @module("@styled-cva/react") @scope("default")
  external aside: (string, 'config) => React.component<'props> = "aside"

  @module("@styled-cva/react") @scope("default")
  external audio: (string, 'config) => React.component<'props> = "audio"

  @module("@styled-cva/react") @scope("default")
  external b: (string, 'config) => React.component<'props> = "b"

  @module("@styled-cva/react") @scope("default")
  external blockquote: (string, 'config) => React.component<'props> = "blockquote"

  @module("@styled-cva/react") @scope("default")
  external button: (string, 'config) => React.component<'props> = "button"

  @module("@styled-cva/react") @scope("default")
  external canvas: (string, 'config) => React.component<'props> = "canvas"

  @module("@styled-cva/react") @scope("default")
  external caption: (string, 'config) => React.component<'props> = "caption"

  @module("@styled-cva/react") @scope("default")
  external cite: (string, 'config) => React.component<'props> = "cite"

  @module("@styled-cva/react") @scope("default")
  external code: (string, 'config) => React.component<'props> = "code"

  @module("@styled-cva/react") @scope("default")
  external dd: (string, 'config) => React.component<'props> = "dd"

  @module("@styled-cva/react") @scope("default")
  external del: (string, 'config) => React.component<'props> = "del"

  @module("@styled-cva/react") @scope("default")
  external details: (string, 'config) => React.component<'props> = "details"

  @module("@styled-cva/react") @scope("default")
  external dfn: (string, 'config) => React.component<'props> = "dfn"

  @module("@styled-cva/react") @scope("default")
  external dialog: (string, 'config) => React.component<'props> = "dialog"

  @module("@styled-cva/react") @scope("default")
  external div: (string, 'config) => React.component<'props> = "div"

  @module("@styled-cva/react") @scope("default")
  external dl: (string, 'config) => React.component<'props> = "dl"

  @module("@styled-cva/react") @scope("default")
  external dt: (string, 'config) => React.component<'props> = "dt"

  @module("@styled-cva/react") @scope("default")
  external em: (string, 'config) => React.component<'props> = "em"

  @module("@styled-cva/react") @scope("default")
  external fieldset: (string, 'config) => React.component<'props> = "fieldset"

  @module("@styled-cva/react") @scope("default")
  external figcaption: (string, 'config) => React.component<'props> = "figcaption"

  @module("@styled-cva/react") @scope("default")
  external figure: (string, 'config) => React.component<'props> = "figure"

  @module("@styled-cva/react") @scope("default")
  external footer: (string, 'config) => React.component<'props> = "footer"

  @module("@styled-cva/react") @scope("default")
  external form: (string, 'config) => React.component<'props> = "form"

  @module("@styled-cva/react") @scope("default")
  external h1: (string, 'config) => React.component<'props> = "h1"

  @module("@styled-cva/react") @scope("default")
  external h2: (string, 'config) => React.component<'props> = "h2"

  @module("@styled-cva/react") @scope("default")
  external h3: (string, 'config) => React.component<'props> = "h3"

  @module("@styled-cva/react") @scope("default")
  external h4: (string, 'config) => React.component<'props> = "h4"

  @module("@styled-cva/react") @scope("default")
  external h5: (string, 'config) => React.component<'props> = "h5"

  @module("@styled-cva/react") @scope("default")
  external h6: (string, 'config) => React.component<'props> = "h6"

  @module("@styled-cva/react") @scope("default")
  external header: (string, 'config) => React.component<'props> = "header"

  @module("@styled-cva/react") @scope("default")
  external hgroup: (string, 'config) => React.component<'props> = "hgroup"

  @module("@styled-cva/react") @scope("default")
  external hr: (string, 'config) => React.component<'props> = "hr"

  @module("@styled-cva/react") @scope("default")
  external i: (string, 'config) => React.component<'props> = "i"

  @module("@styled-cva/react") @scope("default")
  external img: (string, 'config) => React.component<'props> = "img"

  @module("@styled-cva/react") @scope("default")
  external input: (string, 'config) => React.component<'props> = "input"

  @module("@styled-cva/react") @scope("default")
  external ins: (string, 'config) => React.component<'props> = "ins"

  @module("@styled-cva/react") @scope("default")
  external kbd: (string, 'config) => React.component<'props> = "kbd"

  @module("@styled-cva/react") @scope("default")
  external label: (string, 'config) => React.component<'props> = "label"

  @module("@styled-cva/react") @scope("default")
  external legend: (string, 'config) => React.component<'props> = "legend"

  @module("@styled-cva/react") @scope("default")
  external li: (string, 'config) => React.component<'props> = "li"

  @module("@styled-cva/react") @scope("default")
  external main: (string, 'config) => React.component<'props> = "main"

  @module("@styled-cva/react") @scope("default")
  external mark: (string, 'config) => React.component<'props> = "mark"

  @module("@styled-cva/react") @scope("default")
  external nav: (string, 'config) => React.component<'props> = "nav"

  @module("@styled-cva/react") @scope("default")
  external ol: (string, 'config) => React.component<'props> = "ol"

  @module("@styled-cva/react") @scope("default")
  external p: (string, 'config) => React.component<'props> = "p"

  @module("@styled-cva/react") @scope("default")
  external picture: (string, 'config) => React.component<'props> = "picture"

  @module("@styled-cva/react") @scope("default")
  external pre: (string, 'config) => React.component<'props> = "pre"

  @module("@styled-cva/react") @scope("default")
  external progress: (string, 'config) => React.component<'props> = "progress"

  @module("@styled-cva/react") @scope("default")
  external q: (string, 'config) => React.component<'props> = "q"

  @module("@styled-cva/react") @scope("default")
  external section: (string, 'config) => React.component<'props> = "section"

  @module("@styled-cva/react") @scope("default")
  external select: (string, 'config) => React.component<'props> = "select"

  @module("@styled-cva/react") @scope("default")
  external small: (string, 'config) => React.component<'props> = "small"

  @module("@styled-cva/react") @scope("default")
  external span: (string, 'config) => React.component<'props> = "span"

  @module("@styled-cva/react") @scope("default")
  external strong: (string, 'config) => React.component<'props> = "strong"

  @module("@styled-cva/react") @scope("default")
  external sub: (string, 'config) => React.component<'props> = "sub"

  @module("@styled-cva/react") @scope("default")
  external summary: (string, 'config) => React.component<'props> = "summary"

  @module("@styled-cva/react") @scope("default")
  external sup: (string, 'config) => React.component<'props> = "sup"

  @module("@styled-cva/react") @scope("default")
  external table: (string, 'config) => React.component<'props> = "table"

  @module("@styled-cva/react") @scope("default")
  external tbody: (string, 'config) => React.component<'props> = "tbody"

  @module("@styled-cva/react") @scope("default")
  external td: (string, 'config) => React.component<'props> = "td"

  @module("@styled-cva/react") @scope("default")
  external textarea: (string, 'config) => React.component<'props> = "textarea"

  @module("@styled-cva/react") @scope("default")
  external tfoot: (string, 'config) => React.component<'props> = "tfoot"

  @module("@styled-cva/react") @scope("default")
  external th: (string, 'config) => React.component<'props> = "th"

  @module("@styled-cva/react") @scope("default")
  external thead: (string, 'config) => React.component<'props> = "thead"

  @module("@styled-cva/react") @scope("default")
  external time: (string, 'config) => React.component<'props> = "time"

  @module("@styled-cva/react") @scope("default")
  external tr: (string, 'config) => React.component<'props> = "tr"

  @module("@styled-cva/react") @scope("default")
  external ul: (string, 'config) => React.component<'props> = "ul"

  @module("@styled-cva/react") @scope("default")
  external video: (string, 'config) => React.component<'props> = "video"

  @module("@styled-cva/react")
  external custom: (React.component<'props>, string, 'config) => React.component<'props> = "default"
}
